### ISSUE TITLE
Boot Monterey on msi B550 motherboards with a ryzen 5xxx cpu

### ISSUE THREAD

**Issue by AbreuY** [AndryX19/MSI-B550I-MPG-Gaming-Edge-Hackintosh#1]
Hi, I would like to know more about this issue. Can you point me to some related post/trhead about this? Thank you.

**Comment by AndryX19** [comment]
Yes, that's the thread: https://forum.amd-osx.com/threads/cannot-install-macos-monterey-12-1-on-msi-b550-edge-wifi-motherboard.2318/

Atm the solution is switch to another motherboard brand

**Comment by AbreuY** [comment]
Thank you.
